#!/bin/bash

BLOOM_UDEV_FILE_PATH=/etc/udev/rules.d/

if [ -f "${BLOOM_UDEV_FILE_PATH}/99-bloom.rules" ]; then
  sudo rm "$BLOOM_UDEV_FILE_PATH/99-bloom.rules";
fi

if [ -f "/usr/bin/bloom" ]; then
  sudo rm /usr/bin/bloom;
fi
