# We maintain a list of all TDF files here
# We use this list to specify all TDF files as dependencies to some custom commands, so that CMake will run the
# commands whenever any TDF is modified. See the custom commands defined in the root CMakeLists.txt for more.
list(
    APPEND
    TDF_FILES_LIST
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY406.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY4313.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY2313A.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY1614.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY261.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY261A.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY861.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY441.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY212.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY13.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY806.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY45.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY202.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY1627.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY24A.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY461.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY804.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY1604.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY1617.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY1626.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY404.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY1607.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY841.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY13A.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY84A.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY814.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY24.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY2313.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY461A.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY167.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY44.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY1634.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY414.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY43U.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY1624.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY48.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY84.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY417.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY3216.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY214.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY828.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY807.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY3217.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY85.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY1616.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY416.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY44A.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY816.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY1606.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY861A.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY402.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY87.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY817.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY204.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY25.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY88.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY412.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY3224.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY3226.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Tiny/ATTINY3227.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA192A3.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA64B1.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA128C3.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA16A4.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA256A3.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA192C3.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA16C4.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA256A3U.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA32D4.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA256D3.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA16A4U.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA64A1.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA128A1.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA32C4.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA128B1.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA256C3.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA128A4U.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA64D3.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA64A4U.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA64A1U.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA384D3.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA16D4.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA32C3.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA128D3.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA32E5.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA192D3.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA64B3.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA128A3.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA64C3.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA32A4U.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA128A3U.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA128D4.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA256A3BU.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA64A3U.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA32A4.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA128B3.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA16E5.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA64A3.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA192A3U.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA8E5.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA256A3B.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA32D3.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA64D4.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA384C3.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Xmega/ATXMEGA128A1U.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR16DD32.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR128DA28.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR32DD28.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR64DA48.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR16DD14.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR64DB64.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR64DB48.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR128DA32.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR32DA28.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR32DB28.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR64DD14.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR64DA28.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR128DA48.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR32DB32.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR64DB28.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR16DD20.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR64DB32.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR32DA32.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR64DA32.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR32DD32.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR128DB48.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR64DD28.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR32DD20.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR64DA64.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR64DD20.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR32DB48.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR128DB64.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR32DD14.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR128DB32.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR32DA48.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR128DA64.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR128DB28.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR64DD32.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR16DD28.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR16DU14.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR16DU20.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR16DU28.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR16DU32.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR32DU14.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR32DU20.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR32DU28.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR32DU32.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR64DU28.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Dx/AVR64DU32.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Ex/AVR64EA28.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Ex/AVR64EA48.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Ex/AVR64EA32.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Ex/AVR16EA28.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Ex/AVR16EA32.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Ex/AVR16EA48.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Ex/AVR16EB14.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Ex/AVR16EB20.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Ex/AVR16EB28.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Ex/AVR16EB32.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Ex/AVR32EA28.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Ex/AVR32EA32.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Ex/AVR32EA48.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Ex/AVR32EB14.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Ex/AVR32EB20.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Ex/AVR32EB28.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Ex/AVR32EB32.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/AT90USB1287.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA406.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA325P.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/AT90CAN128.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA88.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA164PA.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA88P.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA48A.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA16A.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA1284.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA256RFR2.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA645.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA32C1.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/AT90PWM216.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA169A.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA16.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/AT90USB1286.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA64RFR2.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA4808.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA325.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA168PA.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA32U4.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/AT90USB646.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA6490.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA644A.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA1280.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/AT90CAN32.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA649A.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA644RFR2.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA64C1.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA169P.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/AT90PWM1.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA6450.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA128.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA3290P.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA3250A.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA88A.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA128RFA1.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA1284RFR2.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/AT90PWM316.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA164A.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA16U2.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA645A.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA2564RFR2.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA48PB.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA329P.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA162.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA4809.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA165PA.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA32M1.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA324P.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/AT90PWM161.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA16U4.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA325A.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA3250PA.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA32A.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA324A.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA88PA.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA88PB.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA329.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA16M1.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA6450A.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA168.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA32.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA2560.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA324PA.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA1608.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA64A.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA48PA.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA168A.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA64.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA649P.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA328P.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/AT90USB162.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/AT90CAN64.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA324PB.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA164P.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA328.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA6490A.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/AT90PWM2B.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA64M1.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA1609.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA6490P.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/AT90PWM3B.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA128RFR2.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA649.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA48P.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA2561.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA644PA.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA168P.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA1281.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA48.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA165P.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/AT90PWM81.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA169PA.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/AT90USB647.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA165A.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA644P.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA3209.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/AT90USB82.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA808.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA3290A.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA3250P.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA3250.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA6450P.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA645P.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA3290.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA8U2.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA644.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA168PB.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA1284P.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA640.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA128A.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA329PA.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA325PA.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA3208.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA329A.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA32U2.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA3290PA.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA328PB.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/Avr8/Mega/ATMEGA809.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/RiscV/Wch/CH32X035.xml
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/RiscV/Wch/CH32V003.xml
)

# Because the TDF_FILES_LIST is only used to specify dependencies for some custom commands, there is nothing enforcing
# the maintenance of the list. It will be difficult to notice when the list goes out of sync.
#
# For this reason, we enforce maintenance by comparing the length of TDF_FILES_LIST with a generated list of discovered
# TDF files, and trigger a fatal error if they're out of sync.
file(
    GLOB_RECURSE
    DISCOVERED_TDF_FILES
    ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/*.xml
    LIST_DIRECTORIES false
)
list(LENGTH DISCOVERED_TDF_FILES DISCOVERED_TDF_FILE_COUNT)
list(LENGTH TDF_FILES_LIST SPECIFIED_TDF_FILE_COUNT)

if (${DISCOVERED_TDF_FILE_COUNT} GREATER ${SPECIFIED_TDF_FILE_COUNT})
    message(
        FATAL_ERROR
        "TDF file list is not in sync. Discovered ${DISCOVERED_TDF_FILE_COUNT} TDF files in "
        "${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/ but only ${SPECIFIED_TDF_FILE_COUNT} "
        "have been specified in ${CMAKE_CURRENT_SOURCE_DIR}/src/Targets/TargetDescriptionFiles/TargetDescriptionFiles.cmake "
        "Please review TDF_FILES_LIST in TargetDescriptionFiles.cmake"
    )
endif()
